[2024-08-22 09:43:42 -0400] [23542] [INFO] Starting gunicorn 23.0.0
[2024-08-22 09:43:42 -0400] [23542] [INFO] Listening at: http://0.0.0.0:5000 (23542)
[2024-08-22 09:43:42 -0400] [23542] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2024-08-22 09:43:42 -0400] [23543] [INFO] Booting worker with pid: 23543
[2024-08-22 09:43:42 -0400] [23544] [INFO] Booting worker with pid: 23544
[2024-08-22 09:43:42 -0400] [23545] [INFO] Booting worker with pid: 23545
[2024-08-22 09:43:42 -0400] [23546] [INFO] Booting worker with pid: 23546
[2024-08-22 09:43:44 -0400] [23543] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/oyone/fastapi_project/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/home/oyone/fastapi_project/venv/lib/python3.12/site-packages/uvicorn/workers.py", line 75, in init_process
    super().init_process()
  File "/home/oyone/fastapi_project/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/home/oyone/fastapi_project/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/oyone/fastapi_project/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/oyone/fastapi_project/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/oyone/fastapi_project/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oyone/fastapi_project/venv/lib/python3.12/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/oyone/fastapi_project/main.py", line 3, in <module>
    app = create_app()
          ^^^^^^^^^^^^
  File "/home/oyone/fastapi_project/start_files/app.py", line 13, in create_app
    templates = get_templates()
                ^^^^^^^^^^^^^^^
  File "/home/oyone/fastapi_project/start_files/config.py", line 24, in get_templates
    return Jinja2Templates(directory="start_files/templates")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oyone/fastapi_project/venv/lib/python3.12/site-packages/starlette/templating.py", line 102, in __init__
    assert jinja2 is not None, "jinja2 must be installed to use Jinja2Templates"
           ^^^^^^^^^^^^^^^^^^
AssertionError: jinja2 must be installed to use Jinja2Templates
[2024-08-22 09:43:44 -0400] [23543] [INFO] Worker exiting (pid: 23543)
[2024-08-22 09:43:45 -0400] [23544] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/oyone/fastapi_project/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/home/oyone/fastapi_project/venv/lib/python3.12/site-packages/uvicorn/workers.py", line 75, in init_process
    super().init_process()
  File "/home/oyone/fastapi_project/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/home/oyone/fastapi_project/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/oyone/fastapi_project/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/oyone/fastapi_project/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/oyone/fastapi_project/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oyone/fastapi_project/venv/lib/python3.12/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/oyone/fastapi_project/main.py", line 3, in <module>
    app = create_app()
          ^^^^^^^^^^^^
  File "/home/oyone/fastapi_project/start_files/app.py", line 13, in create_app
    templates = get_templates()
                ^^^^^^^^^^^^^^^
  File "/home/oyone/fastapi_project/start_files/config.py", line 24, in get_templates
    return Jinja2Templates(directory="start_files/templates")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oyone/fastapi_project/venv/lib/python3.12/site-packages/starlette/templating.py", line 102, in __init__
    assert jinja2 is not None, "jinja2 must be installed to use Jinja2Templates"
           ^^^^^^^^^^^^^^^^^^
AssertionError: jinja2 must be installed to use Jinja2Templates
[2024-08-22 09:43:45 -0400] [23544] [INFO] Worker exiting (pid: 23544)
[2024-08-22 09:43:45 -0400] [23545] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/oyone/fastapi_project/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/home/oyone/fastapi_project/venv/lib/python3.12/site-packages/uvicorn/workers.py", line 75, in init_process
    super().init_process()
  File "/home/oyone/fastapi_project/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/home/oyone/fastapi_project/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/oyone/fastapi_project/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/oyone/fastapi_project/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/oyone/fastapi_project/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oyone/fastapi_project/venv/lib/python3.12/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/oyone/fastapi_project/main.py", line 3, in <module>
    app = create_app()
          ^^^^^^^^^^^^
  File "/home/oyone/fastapi_project/start_files/app.py", line 13, in create_app
    templates = get_templates()
                ^^^^^^^^^^^^^^^
  File "/home/oyone/fastapi_project/start_files/config.py", line 24, in get_templates
    return Jinja2Templates(directory="start_files/templates")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oyone/fastapi_project/venv/lib/python3.12/site-packages/starlette/templating.py", line 102, in __init__
    assert jinja2 is not None, "jinja2 must be installed to use Jinja2Templates"
           ^^^^^^^^^^^^^^^^^^
AssertionError: jinja2 must be installed to use Jinja2Templates
[2024-08-22 09:43:45 -0400] [23545] [INFO] Worker exiting (pid: 23545)
[2024-08-22 09:43:45 -0400] [23546] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/oyone/fastapi_project/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/home/oyone/fastapi_project/venv/lib/python3.12/site-packages/uvicorn/workers.py", line 75, in init_process
    super().init_process()
  File "/home/oyone/fastapi_project/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/home/oyone/fastapi_project/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/oyone/fastapi_project/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/oyone/fastapi_project/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/oyone/fastapi_project/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oyone/fastapi_project/venv/lib/python3.12/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/oyone/fastapi_project/main.py", line 3, in <module>
    app = create_app()
          ^^^^^^^^^^^^
  File "/home/oyone/fastapi_project/start_files/app.py", line 13, in create_app
    templates = get_templates()
                ^^^^^^^^^^^^^^^
  File "/home/oyone/fastapi_project/start_files/config.py", line 24, in get_templates
    return Jinja2Templates(directory="start_files/templates")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oyone/fastapi_project/venv/lib/python3.12/site-packages/starlette/templating.py", line 102, in __init__
    assert jinja2 is not None, "jinja2 must be installed to use Jinja2Templates"
           ^^^^^^^^^^^^^^^^^^
AssertionError: jinja2 must be installed to use Jinja2Templates
[2024-08-22 09:43:45 -0400] [23546] [INFO] Worker exiting (pid: 23546)
[2024-08-22 09:43:45 -0400] [23542] [ERROR] Worker (pid:23543) exited with code 3
[2024-08-22 09:43:45 -0400] [23542] [ERROR] Worker (pid:23544) was sent SIGTERM!
[2024-08-22 09:43:45 -0400] [23542] [ERROR] Worker (pid:23545) was sent SIGTERM!
[2024-08-22 09:43:45 -0400] [23542] [ERROR] Worker (pid:23546) was sent SIGTERM!
[2024-08-22 09:43:45 -0400] [23542] [ERROR] Shutting down: Master
[2024-08-22 09:43:45 -0400] [23542] [ERROR] Reason: Worker failed to boot.
[2024-08-22 09:43:53 -0400] [23550] [INFO] Starting gunicorn 23.0.0
[2024-08-22 09:43:53 -0400] [23550] [INFO] Listening at: http://0.0.0.0:5000 (23550)
[2024-08-22 09:43:53 -0400] [23550] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2024-08-22 09:43:53 -0400] [23551] [INFO] Booting worker with pid: 23551
[2024-08-22 09:43:53 -0400] [23552] [INFO] Booting worker with pid: 23552
[2024-08-22 09:43:53 -0400] [23553] [INFO] Booting worker with pid: 23553
[2024-08-22 09:43:53 -0400] [23554] [INFO] Booting worker with pid: 23554
[2024-08-22 09:43:56 -0400] [23551] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/oyone/fastapi_project/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/home/oyone/fastapi_project/venv/lib/python3.12/site-packages/uvicorn/workers.py", line 75, in init_process
    super().init_process()
  File "/home/oyone/fastapi_project/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/home/oyone/fastapi_project/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/oyone/fastapi_project/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/oyone/fastapi_project/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/oyone/fastapi_project/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oyone/fastapi_project/venv/lib/python3.12/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/oyone/fastapi_project/main.py", line 3, in <module>
    app = create_app()
          ^^^^^^^^^^^^
  File "/home/oyone/fastapi_project/start_files/app.py", line 13, in create_app
    templates = get_templates()
                ^^^^^^^^^^^^^^^
  File "/home/oyone/fastapi_project/start_files/config.py", line 24, in get_templates
    return Jinja2Templates(directory="start_files/templates")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oyone/fastapi_project/venv/lib/python3.12/site-packages/starlette/templating.py", line 102, in __init__
    assert jinja2 is not None, "jinja2 must be installed to use Jinja2Templates"
           ^^^^^^^^^^^^^^^^^^
AssertionError: jinja2 must be installed to use Jinja2Templates
[2024-08-22 09:43:56 -0400] [23551] [INFO] Worker exiting (pid: 23551)
[2024-08-22 09:44:08 -0400] [23558] [INFO] Starting gunicorn 23.0.0
[2024-08-22 09:44:08 -0400] [23558] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2024-08-22 09:44:08 -0400] [23558] [ERROR] connection to ('0.0.0.0', 5000) failed: [Errno 98] Address already in use
[2024-08-22 09:44:09 -0400] [23558] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2024-08-22 09:44:09 -0400] [23558] [ERROR] connection to ('0.0.0.0', 5000) failed: [Errno 98] Address already in use
[2024-08-22 09:44:10 -0400] [23558] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2024-08-22 09:44:10 -0400] [23558] [ERROR] connection to ('0.0.0.0', 5000) failed: [Errno 98] Address already in use
[2024-08-22 09:44:11 -0400] [23558] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2024-08-22 09:44:11 -0400] [23558] [ERROR] connection to ('0.0.0.0', 5000) failed: [Errno 98] Address already in use
[2024-08-22 09:44:12 -0400] [23558] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2024-08-22 09:44:12 -0400] [23558] [ERROR] connection to ('0.0.0.0', 5000) failed: [Errno 98] Address already in use
[2024-08-22 09:44:13 -0400] [23558] [ERROR] Can't connect to ('0.0.0.0', 5000)
[2024-08-22 09:45:01 -0400] [23560] [INFO] Starting gunicorn 23.0.0
[2024-08-22 09:45:01 -0400] [23560] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2024-08-22 09:45:01 -0400] [23560] [ERROR] connection to ('0.0.0.0', 5000) failed: [Errno 98] Address already in use
[2024-08-22 09:45:02 -0400] [23560] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2024-08-22 09:45:02 -0400] [23560] [ERROR] connection to ('0.0.0.0', 5000) failed: [Errno 98] Address already in use
[2024-08-22 09:45:03 -0400] [23560] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2024-08-22 09:45:03 -0400] [23560] [ERROR] connection to ('0.0.0.0', 5000) failed: [Errno 98] Address already in use
[2024-08-22 09:45:04 -0400] [23560] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2024-08-22 09:45:04 -0400] [23560] [ERROR] connection to ('0.0.0.0', 5000) failed: [Errno 98] Address already in use
[2024-08-22 09:45:05 -0400] [23560] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2024-08-22 09:45:05 -0400] [23560] [ERROR] connection to ('0.0.0.0', 5000) failed: [Errno 98] Address already in use
[2024-08-22 09:45:06 -0400] [23560] [ERROR] Can't connect to ('0.0.0.0', 5000)
[2024-08-22 09:45:40 -0400] [23568] [INFO] Starting gunicorn 23.0.0
[2024-08-22 09:45:40 -0400] [23568] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2024-08-22 09:45:40 -0400] [23568] [ERROR] connection to ('0.0.0.0', 5000) failed: [Errno 98] Address already in use
[2024-08-22 09:45:41 -0400] [23568] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2024-08-22 09:45:41 -0400] [23568] [ERROR] connection to ('0.0.0.0', 5000) failed: [Errno 98] Address already in use
[2024-08-22 09:45:42 -0400] [23568] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2024-08-22 09:45:42 -0400] [23568] [ERROR] connection to ('0.0.0.0', 5000) failed: [Errno 98] Address already in use
[2024-08-22 09:45:43 -0400] [23568] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2024-08-22 09:45:43 -0400] [23568] [ERROR] connection to ('0.0.0.0', 5000) failed: [Errno 98] Address already in use
[2024-08-22 09:45:44 -0400] [23568] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2024-08-22 09:45:44 -0400] [23568] [ERROR] connection to ('0.0.0.0', 5000) failed: [Errno 98] Address already in use
[2024-08-22 09:45:45 -0400] [23568] [ERROR] Can't connect to ('0.0.0.0', 5000)
[2024-08-22 09:46:59 -0400] [23589] [DEBUG] Current configuration:
  config: gunicorn_config.py
  wsgi_app: None
  bind: ['0.0.0.0:5000']
  backlog: 2048
  workers: 4
  worker_class: uvicorn.workers.UvicornWorker
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /home/oyone/fastapi_project
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 1000
  group: 1003
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1', '::1']
  accesslog: /home/oyone/fastapi_project/logs/access.log
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: /home/oyone/fastapi_project/logs/error.log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  logconfig_json: None
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: main:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0xffffb33ec180>
  on_reload: <function OnReload.on_reload at 0xffffb33ec2c0>
  when_ready: <function WhenReady.when_ready at 0xffffb33ec400>
  pre_fork: <function Prefork.pre_fork at 0xffffb33ec5e0>
  post_fork: <function Postfork.post_fork at 0xffffb33ec720>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0xffffb33ec860>
  worker_int: <function WorkerInt.worker_int at 0xffffb33ec9a0>
  worker_abort: <function WorkerAbort.worker_abort at 0xffffb33ecae0>
  pre_exec: <function PreExec.pre_exec at 0xffffb33ecc20>
  pre_request: <function PreRequest.pre_request at 0xffffb33ecd60>
  post_request: <function PostRequest.post_request at 0xffffb33ece00>
  child_exit: <function ChildExit.child_exit at 0xffffb33ecf40>
  worker_exit: <function WorkerExit.worker_exit at 0xffffb33ed080>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0xffffb33ed1c0>
  on_exit: <function OnExit.on_exit at 0xffffb33ed300>
  ssl_context: <function NewSSLContext.ssl_context at 0xffffb33ed4e0>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1', '::1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  permit_obsolete_folding: False
  strip_header_spaces: False
  permit_unconventional_http_method: False
  permit_unconventional_http_version: False
  casefold_http_method: False
  forwarder_headers: ['SCRIPT_NAME', 'PATH_INFO']
  header_map: drop
[2024-08-22 09:46:59 -0400] [23589] [INFO] Starting gunicorn 23.0.0
[2024-08-22 09:46:59 -0400] [23589] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2024-08-22 09:46:59 -0400] [23589] [ERROR] connection to ('0.0.0.0', 5000) failed: [Errno 98] Address already in use
[2024-08-22 09:46:59 -0400] [23589] [DEBUG] Retrying in 1 second.
[2024-08-22 09:47:00 -0400] [23589] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2024-08-22 09:47:00 -0400] [23589] [ERROR] connection to ('0.0.0.0', 5000) failed: [Errno 98] Address already in use
[2024-08-22 09:47:00 -0400] [23589] [DEBUG] Retrying in 1 second.
[2024-08-22 09:47:01 -0400] [23589] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2024-08-22 09:47:01 -0400] [23589] [ERROR] connection to ('0.0.0.0', 5000) failed: [Errno 98] Address already in use
[2024-08-22 09:47:01 -0400] [23589] [DEBUG] Retrying in 1 second.
[2024-08-22 09:47:02 -0400] [23589] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2024-08-22 09:47:02 -0400] [23589] [ERROR] connection to ('0.0.0.0', 5000) failed: [Errno 98] Address already in use
[2024-08-22 09:47:02 -0400] [23589] [DEBUG] Retrying in 1 second.
[2024-08-22 09:47:03 -0400] [23589] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2024-08-22 09:47:03 -0400] [23589] [ERROR] connection to ('0.0.0.0', 5000) failed: [Errno 98] Address already in use
[2024-08-22 09:47:03 -0400] [23589] [DEBUG] Retrying in 1 second.
[2024-08-22 09:47:04 -0400] [23589] [ERROR] Can't connect to ('0.0.0.0', 5000)
[2024-08-22 09:47:21 -0400] [23591] [DEBUG] Current configuration:
  config: gunicorn_config.py
  wsgi_app: None
  bind: ['0.0.0.0:5000']
  backlog: 2048
  workers: 2
  worker_class: uvicorn.workers.UvicornWorker
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /home/oyone/fastapi_project
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 1000
  group: 1003
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1', '::1']
  accesslog: /home/oyone/fastapi_project/logs/access.log
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: /home/oyone/fastapi_project/logs/error.log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  logconfig_json: None
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: main:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0xffffb293c180>
  on_reload: <function OnReload.on_reload at 0xffffb293c2c0>
  when_ready: <function WhenReady.when_ready at 0xffffb293c400>
  pre_fork: <function Prefork.pre_fork at 0xffffb293c5e0>
  post_fork: <function Postfork.post_fork at 0xffffb293c720>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0xffffb293c860>
  worker_int: <function WorkerInt.worker_int at 0xffffb293c9a0>
  worker_abort: <function WorkerAbort.worker_abort at 0xffffb293cae0>
  pre_exec: <function PreExec.pre_exec at 0xffffb293cc20>
  pre_request: <function PreRequest.pre_request at 0xffffb293cd60>
  post_request: <function PostRequest.post_request at 0xffffb293ce00>
  child_exit: <function ChildExit.child_exit at 0xffffb293cf40>
  worker_exit: <function WorkerExit.worker_exit at 0xffffb293d080>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0xffffb293d1c0>
  on_exit: <function OnExit.on_exit at 0xffffb293d300>
  ssl_context: <function NewSSLContext.ssl_context at 0xffffb293d4e0>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1', '::1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  permit_obsolete_folding: False
  strip_header_spaces: False
  permit_unconventional_http_method: False
  permit_unconventional_http_version: False
  casefold_http_method: False
  forwarder_headers: ['SCRIPT_NAME', 'PATH_INFO']
  header_map: drop
[2024-08-22 09:47:21 -0400] [23591] [INFO] Starting gunicorn 23.0.0
[2024-08-22 09:47:21 -0400] [23591] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2024-08-22 09:47:21 -0400] [23591] [ERROR] connection to ('0.0.0.0', 5000) failed: [Errno 98] Address already in use
[2024-08-22 09:47:21 -0400] [23591] [DEBUG] Retrying in 1 second.
[2024-08-22 09:47:22 -0400] [23591] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2024-08-22 09:47:22 -0400] [23591] [ERROR] connection to ('0.0.0.0', 5000) failed: [Errno 98] Address already in use
[2024-08-22 09:47:22 -0400] [23591] [DEBUG] Retrying in 1 second.
[2024-08-22 09:47:23 -0400] [23591] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2024-08-22 09:47:23 -0400] [23591] [ERROR] connection to ('0.0.0.0', 5000) failed: [Errno 98] Address already in use
[2024-08-22 09:47:23 -0400] [23591] [DEBUG] Retrying in 1 second.
[2024-08-22 09:47:24 -0400] [23591] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2024-08-22 09:47:24 -0400] [23591] [ERROR] connection to ('0.0.0.0', 5000) failed: [Errno 98] Address already in use
[2024-08-22 09:47:24 -0400] [23591] [DEBUG] Retrying in 1 second.
[2024-08-22 09:47:25 -0400] [23591] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2024-08-22 09:47:25 -0400] [23591] [ERROR] connection to ('0.0.0.0', 5000) failed: [Errno 98] Address already in use
[2024-08-22 09:47:25 -0400] [23591] [DEBUG] Retrying in 1 second.
[2024-08-22 09:47:26 -0400] [23591] [ERROR] Can't connect to ('0.0.0.0', 5000)
[2024-08-22 09:47:55 -0400] [23596] [DEBUG] Current configuration:
  config: gunicorn_config.py
  wsgi_app: None
  bind: ['127.0.0.0.1:5000']
  backlog: 2048
  workers: 2
  worker_class: uvicorn.workers.UvicornWorker
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /home/oyone/fastapi_project
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 1000
  group: 1003
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1', '::1']
  accesslog: /home/oyone/fastapi_project/logs/access.log
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: /home/oyone/fastapi_project/logs/error.log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  logconfig_json: None
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: main:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0xffff91d6c180>
  on_reload: <function OnReload.on_reload at 0xffff91d6c2c0>
  when_ready: <function WhenReady.when_ready at 0xffff91d6c400>
  pre_fork: <function Prefork.pre_fork at 0xffff91d6c5e0>
  post_fork: <function Postfork.post_fork at 0xffff91d6c720>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0xffff91d6c860>
  worker_int: <function WorkerInt.worker_int at 0xffff91d6c9a0>
  worker_abort: <function WorkerAbort.worker_abort at 0xffff91d6cae0>
  pre_exec: <function PreExec.pre_exec at 0xffff91d6cc20>
  pre_request: <function PreRequest.pre_request at 0xffff91d6cd60>
  post_request: <function PostRequest.post_request at 0xffff91d6ce00>
  child_exit: <function ChildExit.child_exit at 0xffff91d6cf40>
  worker_exit: <function WorkerExit.worker_exit at 0xffff91d6d080>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0xffff91d6d1c0>
  on_exit: <function OnExit.on_exit at 0xffff91d6d300>
  ssl_context: <function NewSSLContext.ssl_context at 0xffff91d6d4e0>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1', '::1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  permit_obsolete_folding: False
  strip_header_spaces: False
  permit_unconventional_http_method: False
  permit_unconventional_http_version: False
  casefold_http_method: False
  forwarder_headers: ['SCRIPT_NAME', 'PATH_INFO']
  header_map: drop
[2024-08-22 09:47:55 -0400] [23596] [INFO] Starting gunicorn 23.0.0
[2024-08-22 09:47:55 -0400] [23596] [ERROR] connection to ('127.0.0.0.1', 5000) failed: [Errno -2] Name or service not known
[2024-08-22 09:47:55 -0400] [23596] [DEBUG] Retrying in 1 second.
[2024-08-22 09:47:56 -0400] [23596] [ERROR] connection to ('127.0.0.0.1', 5000) failed: [Errno -2] Name or service not known
[2024-08-22 09:47:56 -0400] [23596] [DEBUG] Retrying in 1 second.
[2024-08-22 09:47:57 -0400] [23596] [ERROR] connection to ('127.0.0.0.1', 5000) failed: [Errno -2] Name or service not known
[2024-08-22 09:47:57 -0400] [23596] [DEBUG] Retrying in 1 second.
[2024-08-22 09:47:58 -0400] [23596] [ERROR] connection to ('127.0.0.0.1', 5000) failed: [Errno -2] Name or service not known
[2024-08-22 09:47:58 -0400] [23596] [DEBUG] Retrying in 1 second.
[2024-08-22 09:47:59 -0400] [23596] [ERROR] connection to ('127.0.0.0.1', 5000) failed: [Errno -2] Name or service not known
[2024-08-22 09:47:59 -0400] [23596] [DEBUG] Retrying in 1 second.
[2024-08-22 09:48:00 -0400] [23596] [ERROR] Can't connect to ('127.0.0.0.1', 5000)
[2024-08-24 03:08:27 -0400] [1498] [DEBUG] Current configuration:
  config: gunicorn_config.py
  wsgi_app: None
  bind: ['127.0.0.1:5000']
  backlog: 2048
  workers: 2
  worker_class: uvicorn.workers.UvicornWorker
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /home/oyone/fastapi_project
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 1000
  group: 1003
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1', '::1']
  accesslog: /home/oyone/fastapi_project/logs/access.log
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: /home/oyone/fastapi_project/logs/error.log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  logconfig_json: None
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: main:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0xffff8e3fc180>
  on_reload: <function OnReload.on_reload at 0xffff8e3fc2c0>
  when_ready: <function WhenReady.when_ready at 0xffff8e3fc400>
  pre_fork: <function Prefork.pre_fork at 0xffff8e3fc5e0>
  post_fork: <function Postfork.post_fork at 0xffff8e3fc720>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0xffff8e3fc860>
  worker_int: <function WorkerInt.worker_int at 0xffff8e3fc9a0>
  worker_abort: <function WorkerAbort.worker_abort at 0xffff8e3fcae0>
  pre_exec: <function PreExec.pre_exec at 0xffff8e3fcc20>
  pre_request: <function PreRequest.pre_request at 0xffff8e3fcd60>
  post_request: <function PostRequest.post_request at 0xffff8e3fce00>
  child_exit: <function ChildExit.child_exit at 0xffff8e3fcf40>
  worker_exit: <function WorkerExit.worker_exit at 0xffff8e3fd080>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0xffff8e3fd1c0>
  on_exit: <function OnExit.on_exit at 0xffff8e3fd300>
  ssl_context: <function NewSSLContext.ssl_context at 0xffff8e3fd4e0>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1', '::1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  permit_obsolete_folding: False
  strip_header_spaces: False
  permit_unconventional_http_method: False
  permit_unconventional_http_version: False
  casefold_http_method: False
  forwarder_headers: ['SCRIPT_NAME', 'PATH_INFO']
  header_map: drop
[2024-08-24 03:08:27 -0400] [1498] [INFO] Starting gunicorn 23.0.0
[2024-08-24 03:08:27 -0400] [1498] [DEBUG] Arbiter booted
[2024-08-24 03:08:27 -0400] [1498] [INFO] Listening at: http://127.0.0.1:5000 (1498)
[2024-08-24 03:08:27 -0400] [1498] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2024-08-24 03:08:27 -0400] [1499] [INFO] Booting worker with pid: 1499
[2024-08-24 03:08:27 -0400] [1500] [INFO] Booting worker with pid: 1500
[2024-08-24 03:08:27 -0400] [1498] [DEBUG] 2 workers
[2024-08-24 03:08:30 -0400] [1499] [INFO] Started server process [1499]
[2024-08-24 03:08:30 -0400] [1500] [INFO] Started server process [1500]
[2024-08-24 03:08:30 -0400] [1499] [INFO] Waiting for application startup.
[2024-08-24 03:08:30 -0400] [1500] [INFO] Waiting for application startup.
[2024-08-24 03:08:30 -0400] [1500] [INFO] Application startup complete.
[2024-08-24 03:08:30 -0400] [1499] [INFO] Application startup complete.
[2024-08-24 03:08:51 -0400] [1498] [INFO] Handling signal: int
[2024-08-24 03:08:51 -0400] [1500] [INFO] Shutting down
[2024-08-24 03:08:51 -0400] [1499] [INFO] Shutting down
[2024-08-24 03:08:51 -0400] [1500] [INFO] Waiting for application shutdown.
[2024-08-24 03:08:51 -0400] [1499] [INFO] Waiting for application shutdown.
[2024-08-24 03:08:51 -0400] [1500] [INFO] Application shutdown complete.
[2024-08-24 03:08:51 -0400] [1499] [INFO] Application shutdown complete.
[2024-08-24 03:08:51 -0400] [1500] [INFO] Finished server process [1500]
[2024-08-24 03:08:51 -0400] [1499] [INFO] Finished server process [1499]
[2024-08-24 03:08:51 -0400] [1498] [ERROR] Worker (pid:1499) was sent SIGINT!
[2024-08-24 03:08:51 -0400] [1498] [ERROR] Worker (pid:1500) was sent SIGINT!
[2024-08-24 03:08:51 -0400] [1498] [INFO] Shutting down: Master
[2024-08-24 03:09:09 -0400] [1504] [INFO] Starting gunicorn 23.0.0
[2024-08-24 03:09:09 -0400] [1504] [INFO] Listening at: http://127.0.0.1:5000 (1504)
[2024-08-24 03:09:09 -0400] [1504] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2024-08-24 03:09:09 -0400] [1505] [INFO] Booting worker with pid: 1505
[2024-08-24 03:09:09 -0400] [1506] [INFO] Booting worker with pid: 1506
[2024-08-24 03:09:11 -0400] [1505] [INFO] Started server process [1505]
[2024-08-24 03:09:11 -0400] [1505] [INFO] Waiting for application startup.
[2024-08-24 03:09:11 -0400] [1505] [INFO] Application startup complete.
[2024-08-24 03:09:11 -0400] [1506] [INFO] Started server process [1506]
[2024-08-24 03:09:11 -0400] [1506] [INFO] Waiting for application startup.
[2024-08-24 03:09:11 -0400] [1506] [INFO] Application startup complete.
[2024-08-24 03:09:38 -0400] [1511] [DEBUG] Current configuration:
  config: gunicorn_config.py
  wsgi_app: None
  bind: ['127.0.0.1:5000']
  backlog: 2048
  workers: 2
  worker_class: uvicorn.workers.UvicornWorker
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /home/oyone/fastapi_project
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 1000
  group: 1003
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1', '::1']
  accesslog: /home/oyone/fastapi_project/logs/access.log
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: /home/oyone/fastapi_project/logs/error.log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  logconfig_json: None
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: main:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0xffff9455c180>
  on_reload: <function OnReload.on_reload at 0xffff9455c2c0>
  when_ready: <function WhenReady.when_ready at 0xffff9455c400>
  pre_fork: <function Prefork.pre_fork at 0xffff9455c5e0>
  post_fork: <function Postfork.post_fork at 0xffff9455c720>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0xffff9455c860>
  worker_int: <function WorkerInt.worker_int at 0xffff9455c9a0>
  worker_abort: <function WorkerAbort.worker_abort at 0xffff9455cae0>
  pre_exec: <function PreExec.pre_exec at 0xffff9455cc20>
  pre_request: <function PreRequest.pre_request at 0xffff9455cd60>
  post_request: <function PostRequest.post_request at 0xffff9455ce00>
  child_exit: <function ChildExit.child_exit at 0xffff9455cf40>
  worker_exit: <function WorkerExit.worker_exit at 0xffff9455d080>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0xffff9455d1c0>
  on_exit: <function OnExit.on_exit at 0xffff9455d300>
  ssl_context: <function NewSSLContext.ssl_context at 0xffff9455d4e0>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1', '::1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  permit_obsolete_folding: False
  strip_header_spaces: False
  permit_unconventional_http_method: False
  permit_unconventional_http_version: False
  casefold_http_method: False
  forwarder_headers: ['SCRIPT_NAME', 'PATH_INFO']
  header_map: drop
[2024-08-24 03:09:38 -0400] [1511] [INFO] Starting gunicorn 23.0.0
[2024-08-24 03:09:38 -0400] [1511] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2024-08-24 03:09:38 -0400] [1511] [ERROR] connection to ('127.0.0.1', 5000) failed: [Errno 98] Address already in use
[2024-08-24 03:09:38 -0400] [1511] [DEBUG] Retrying in 1 second.
[2024-08-24 03:09:39 -0400] [1511] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2024-08-24 03:09:39 -0400] [1511] [ERROR] connection to ('127.0.0.1', 5000) failed: [Errno 98] Address already in use
[2024-08-24 03:09:39 -0400] [1511] [DEBUG] Retrying in 1 second.
[2024-08-24 03:09:40 -0400] [1511] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2024-08-24 03:09:40 -0400] [1511] [ERROR] connection to ('127.0.0.1', 5000) failed: [Errno 98] Address already in use
[2024-08-24 03:09:40 -0400] [1511] [DEBUG] Retrying in 1 second.
[2024-08-24 03:09:41 -0400] [1511] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2024-08-24 03:09:41 -0400] [1511] [ERROR] connection to ('127.0.0.1', 5000) failed: [Errno 98] Address already in use
[2024-08-24 03:09:41 -0400] [1511] [DEBUG] Retrying in 1 second.
[2024-08-24 03:09:42 -0400] [1511] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2024-08-24 03:09:42 -0400] [1511] [ERROR] connection to ('127.0.0.1', 5000) failed: [Errno 98] Address already in use
[2024-08-24 03:09:42 -0400] [1511] [DEBUG] Retrying in 1 second.
[2024-08-24 03:09:43 -0400] [1511] [ERROR] Can't connect to ('127.0.0.1', 5000)
[2024-08-24 03:09:52 -0400] [1512] [DEBUG] Current configuration:
  config: gunicorn_config.py
  wsgi_app: None
  bind: ['127.0.0.1:5000']
  backlog: 2048
  workers: 2
  worker_class: uvicorn.workers.UvicornWorker
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /home/oyone/fastapi_project
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 1000
  group: 1003
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1', '::1']
  accesslog: /home/oyone/fastapi_project/logs/access.log
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: /home/oyone/fastapi_project/logs/error.log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  logconfig_json: None
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: main:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0xffffb87fc180>
  on_reload: <function OnReload.on_reload at 0xffffb87fc2c0>
  when_ready: <function WhenReady.when_ready at 0xffffb87fc400>
  pre_fork: <function Prefork.pre_fork at 0xffffb87fc5e0>
  post_fork: <function Postfork.post_fork at 0xffffb87fc720>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0xffffb87fc860>
  worker_int: <function WorkerInt.worker_int at 0xffffb87fc9a0>
  worker_abort: <function WorkerAbort.worker_abort at 0xffffb87fcae0>
  pre_exec: <function PreExec.pre_exec at 0xffffb87fcc20>
  pre_request: <function PreRequest.pre_request at 0xffffb87fcd60>
  post_request: <function PostRequest.post_request at 0xffffb87fce00>
  child_exit: <function ChildExit.child_exit at 0xffffb87fcf40>
  worker_exit: <function WorkerExit.worker_exit at 0xffffb87fd080>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0xffffb87fd1c0>
  on_exit: <function OnExit.on_exit at 0xffffb87fd300>
  ssl_context: <function NewSSLContext.ssl_context at 0xffffb87fd4e0>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1', '::1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  permit_obsolete_folding: False
  strip_header_spaces: False
  permit_unconventional_http_method: False
  permit_unconventional_http_version: False
  casefold_http_method: False
  forwarder_headers: ['SCRIPT_NAME', 'PATH_INFO']
  header_map: drop
[2024-08-24 03:09:52 -0400] [1512] [INFO] Starting gunicorn 23.0.0
[2024-08-24 03:09:52 -0400] [1512] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2024-08-24 03:09:52 -0400] [1512] [ERROR] connection to ('127.0.0.1', 5000) failed: [Errno 98] Address already in use
[2024-08-24 03:09:52 -0400] [1512] [DEBUG] Retrying in 1 second.
[2024-08-24 03:09:53 -0400] [1512] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2024-08-24 03:09:53 -0400] [1512] [ERROR] connection to ('127.0.0.1', 5000) failed: [Errno 98] Address already in use
[2024-08-24 03:09:53 -0400] [1512] [DEBUG] Retrying in 1 second.
[2024-08-24 03:09:54 -0400] [1512] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2024-08-24 03:09:54 -0400] [1512] [ERROR] connection to ('127.0.0.1', 5000) failed: [Errno 98] Address already in use
[2024-08-24 03:09:54 -0400] [1512] [DEBUG] Retrying in 1 second.
[2024-08-24 03:09:55 -0400] [1512] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2024-08-24 03:09:55 -0400] [1512] [ERROR] connection to ('127.0.0.1', 5000) failed: [Errno 98] Address already in use
[2024-08-24 03:09:55 -0400] [1512] [DEBUG] Retrying in 1 second.
[2024-08-24 03:09:56 -0400] [1512] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2024-08-24 03:09:56 -0400] [1512] [ERROR] connection to ('127.0.0.1', 5000) failed: [Errno 98] Address already in use
[2024-08-24 03:09:56 -0400] [1512] [DEBUG] Retrying in 1 second.
[2024-08-24 03:11:02 -0400] [1526] [DEBUG] Current configuration:
  config: gunicorn_config.py
  wsgi_app: None
  bind: ['192.168.0.19:5000']
  backlog: 2048
  workers: 2
  worker_class: uvicorn.workers.UvicornWorker
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /home/oyone/fastapi_project
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 1000
  group: 1003
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1', '::1']
  accesslog: /home/oyone/fastapi_project/logs/access.log
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: /home/oyone/fastapi_project/logs/error.log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  logconfig_json: None
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: main:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0xffffac71c180>
  on_reload: <function OnReload.on_reload at 0xffffac71c2c0>
  when_ready: <function WhenReady.when_ready at 0xffffac71c400>
  pre_fork: <function Prefork.pre_fork at 0xffffac71c5e0>
  post_fork: <function Postfork.post_fork at 0xffffac71c720>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0xffffac71c860>
  worker_int: <function WorkerInt.worker_int at 0xffffac71c9a0>
  worker_abort: <function WorkerAbort.worker_abort at 0xffffac71cae0>
  pre_exec: <function PreExec.pre_exec at 0xffffac71cc20>
  pre_request: <function PreRequest.pre_request at 0xffffac71cd60>
  post_request: <function PostRequest.post_request at 0xffffac71ce00>
  child_exit: <function ChildExit.child_exit at 0xffffac71cf40>
  worker_exit: <function WorkerExit.worker_exit at 0xffffac71d080>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0xffffac71d1c0>
  on_exit: <function OnExit.on_exit at 0xffffac71d300>
  ssl_context: <function NewSSLContext.ssl_context at 0xffffac71d4e0>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1', '::1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  permit_obsolete_folding: False
  strip_header_spaces: False
  permit_unconventional_http_method: False
  permit_unconventional_http_version: False
  casefold_http_method: False
  forwarder_headers: ['SCRIPT_NAME', 'PATH_INFO']
  header_map: drop
[2024-08-24 03:11:02 -0400] [1526] [INFO] Starting gunicorn 23.0.0
[2024-08-24 03:11:02 -0400] [1526] [DEBUG] Arbiter booted
[2024-08-24 03:11:02 -0400] [1526] [INFO] Listening at: http://192.168.0.19:5000 (1526)
[2024-08-24 03:11:02 -0400] [1526] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2024-08-24 03:11:02 -0400] [1527] [INFO] Booting worker with pid: 1527
[2024-08-24 03:11:02 -0400] [1528] [INFO] Booting worker with pid: 1528
[2024-08-24 03:11:03 -0400] [1526] [DEBUG] 2 workers
[2024-08-24 03:11:05 -0400] [1527] [INFO] Started server process [1527]
[2024-08-24 03:11:05 -0400] [1528] [INFO] Started server process [1528]
[2024-08-24 03:11:06 -0400] [1527] [INFO] Waiting for application startup.
[2024-08-24 03:11:06 -0400] [1528] [INFO] Waiting for application startup.
[2024-08-24 03:11:06 -0400] [1527] [INFO] Application startup complete.
[2024-08-24 03:11:06 -0400] [1528] [INFO] Application startup complete.
[2024-08-24 03:11:23 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:23 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:23 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:23 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:23 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:23 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:23 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:23 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:23 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:23 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:23 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:23 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:23 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:23 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:23 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:23 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:23 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:23 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:23 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:23 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:23 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:23 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:23 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:23 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:23 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:23 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:23 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:23 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:23 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:23 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:23 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:23 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:23 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:23 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:23 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:23 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:23 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:23 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:23 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:23 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:23 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:23 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:24 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:24 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:24 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:24 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:24 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:24 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:24 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:24 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:24 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:24 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:24 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:24 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:24 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:24 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:24 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:24 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:24 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:24 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:24 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:24 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:24 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:24 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:24 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:24 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:24 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:24 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:24 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:24 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:24 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:24 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:24 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:24 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:24 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:24 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:24 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:24 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:24 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:24 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:24 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:24 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:24 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:24 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:25 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:25 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:25 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:25 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:25 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:25 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:25 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:25 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:25 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:25 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:25 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:25 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:25 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:25 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:25 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:25 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:25 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:25 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:25 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:25 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:25 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:25 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:25 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:25 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:25 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:25 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:26 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:26 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:26 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:26 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:26 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:26 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:26 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:26 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:26 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:26 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:26 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:26 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:35 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:35 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:35 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:35 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:35 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:35 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:35 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:35 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:35 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:35 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:35 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:35 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:35 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:35 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:35 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:35 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:35 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:35 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:36 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:36 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:36 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:36 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:36 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:36 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:36 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:36 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:36 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:36 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:36 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:36 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:36 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:36 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:36 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:36 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:36 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:36 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:36 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:36 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:36 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:36 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:36 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:36 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:36 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:36 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:36 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:36 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:36 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:36 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:36 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:36 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:36 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:36 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:36 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:36 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:11:36 -0400] [1526] [INFO] Handling signal: winch
[2024-08-24 03:11:36 -0400] [1526] [DEBUG] SIGWINCH ignored. Not daemonized
[2024-08-24 03:12:26 -0400] [1526] [INFO] Handling signal: int
[2024-08-24 03:12:26 -0400] [1527] [INFO] Shutting down
[2024-08-24 03:12:26 -0400] [1528] [INFO] Shutting down
[2024-08-24 03:12:26 -0400] [1528] [INFO] Waiting for application shutdown.
[2024-08-24 03:12:26 -0400] [1527] [INFO] Waiting for application shutdown.
[2024-08-24 03:12:26 -0400] [1527] [INFO] Application shutdown complete.
[2024-08-24 03:12:26 -0400] [1528] [INFO] Application shutdown complete.
[2024-08-24 03:12:26 -0400] [1527] [INFO] Finished server process [1527]
[2024-08-24 03:12:26 -0400] [1528] [INFO] Finished server process [1528]
[2024-08-24 03:12:26 -0400] [1526] [ERROR] Worker (pid:1527) was sent SIGINT!
[2024-08-24 03:12:26 -0400] [1526] [ERROR] Worker (pid:1528) was sent SIGINT!
[2024-08-24 03:12:26 -0400] [1526] [INFO] Shutting down: Master
[2024-08-24 03:12:38 -0400] [1540] [DEBUG] Current configuration:
  config: gunicorn_config.py
  wsgi_app: None
  bind: ['192.168.0.19:5000']
  backlog: 2048
  workers: 2
  worker_class: uvicorn.workers.UvicornWorker
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /home/oyone/fastapi_project
  daemon: True
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 1000
  group: 1003
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1', '::1']
  accesslog: /home/oyone/fastapi_project/logs/access.log
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: /home/oyone/fastapi_project/logs/error.log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  logconfig_json: None
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: main:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0xffff867ec180>
  on_reload: <function OnReload.on_reload at 0xffff867ec2c0>
  when_ready: <function WhenReady.when_ready at 0xffff867ec400>
  pre_fork: <function Prefork.pre_fork at 0xffff867ec5e0>
  post_fork: <function Postfork.post_fork at 0xffff867ec720>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0xffff867ec860>
  worker_int: <function WorkerInt.worker_int at 0xffff867ec9a0>
  worker_abort: <function WorkerAbort.worker_abort at 0xffff867ecae0>
  pre_exec: <function PreExec.pre_exec at 0xffff867ecc20>
  pre_request: <function PreRequest.pre_request at 0xffff867ecd60>
  post_request: <function PostRequest.post_request at 0xffff867ece00>
  child_exit: <function ChildExit.child_exit at 0xffff867ecf40>
  worker_exit: <function WorkerExit.worker_exit at 0xffff867ed080>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0xffff867ed1c0>
  on_exit: <function OnExit.on_exit at 0xffff867ed300>
  ssl_context: <function NewSSLContext.ssl_context at 0xffff867ed4e0>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1', '::1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  permit_obsolete_folding: False
  strip_header_spaces: False
  permit_unconventional_http_method: False
  permit_unconventional_http_version: False
  casefold_http_method: False
  forwarder_headers: ['SCRIPT_NAME', 'PATH_INFO']
  header_map: drop
[2024-08-24 03:12:38 -0400] [1540] [INFO] Starting gunicorn 23.0.0
[2024-08-24 03:12:38 -0400] [1540] [DEBUG] Arbiter booted
[2024-08-24 03:12:38 -0400] [1540] [INFO] Listening at: http://192.168.0.19:5000 (1540)
[2024-08-24 03:12:38 -0400] [1540] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2024-08-24 03:12:38 -0400] [1541] [INFO] Booting worker with pid: 1541
[2024-08-24 03:12:38 -0400] [1542] [INFO] Booting worker with pid: 1542
[2024-08-24 03:12:38 -0400] [1540] [DEBUG] 2 workers
[2024-08-24 03:12:40 -0400] [1541] [INFO] Started server process [1541]
[2024-08-24 03:12:40 -0400] [1541] [INFO] Waiting for application startup.
[2024-08-24 03:12:40 -0400] [1541] [INFO] Application startup complete.
[2024-08-24 03:12:41 -0400] [1542] [INFO] Started server process [1542]
[2024-08-24 03:12:41 -0400] [1542] [INFO] Waiting for application startup.
[2024-08-24 03:12:41 -0400] [1542] [INFO] Application startup complete.
[2024-08-26 09:08:18 -0400] [12742] [INFO] Starting gunicorn 23.0.0
[2024-08-26 09:08:18 -0400] [12742] [ERROR] Connection in use: ('192.168.0.100', 5000)
[2024-08-26 09:08:18 -0400] [12742] [ERROR] connection to ('192.168.0.100', 5000) failed: [Errno 98] Address already in use
[2024-08-26 09:08:19 -0400] [12742] [ERROR] Connection in use: ('192.168.0.100', 5000)
[2024-08-26 09:08:19 -0400] [12742] [ERROR] connection to ('192.168.0.100', 5000) failed: [Errno 98] Address already in use
[2024-08-26 09:08:20 -0400] [12742] [ERROR] Connection in use: ('192.168.0.100', 5000)
[2024-08-26 09:08:20 -0400] [12742] [ERROR] connection to ('192.168.0.100', 5000) failed: [Errno 98] Address already in use
[2024-08-26 09:08:21 -0400] [12742] [ERROR] Connection in use: ('192.168.0.100', 5000)
[2024-08-26 09:08:21 -0400] [12742] [ERROR] connection to ('192.168.0.100', 5000) failed: [Errno 98] Address already in use
[2024-08-26 09:08:22 -0400] [12742] [ERROR] Connection in use: ('192.168.0.100', 5000)
[2024-08-26 09:08:22 -0400] [12742] [ERROR] connection to ('192.168.0.100', 5000) failed: [Errno 98] Address already in use
[2024-08-26 09:08:23 -0400] [12742] [ERROR] Can't connect to ('192.168.0.100', 5000)
[2024-08-26 09:14:29 -0400] [1772] [INFO] Starting gunicorn 23.0.0
[2024-08-26 09:14:29 -0400] [1772] [ERROR] Connection in use: ('192.168.0.100', 5000)
[2024-08-26 09:14:29 -0400] [1772] [ERROR] connection to ('192.168.0.100', 5000) failed: [Errno 98] Address already in use
[2024-08-26 09:14:30 -0400] [1772] [ERROR] Connection in use: ('192.168.0.100', 5000)
[2024-08-26 09:14:30 -0400] [1772] [ERROR] connection to ('192.168.0.100', 5000) failed: [Errno 98] Address already in use
[2024-08-26 09:14:31 -0400] [1772] [ERROR] Connection in use: ('192.168.0.100', 5000)
[2024-08-26 09:14:31 -0400] [1772] [ERROR] connection to ('192.168.0.100', 5000) failed: [Errno 98] Address already in use
[2024-08-26 09:14:32 -0400] [1772] [ERROR] Connection in use: ('192.168.0.100', 5000)
[2024-08-26 09:14:32 -0400] [1772] [ERROR] connection to ('192.168.0.100', 5000) failed: [Errno 98] Address already in use
[2024-08-26 09:14:33 -0400] [1772] [ERROR] Connection in use: ('192.168.0.100', 5000)
[2024-08-26 09:14:33 -0400] [1772] [ERROR] connection to ('192.168.0.100', 5000) failed: [Errno 98] Address already in use
[2024-08-26 09:14:34 -0400] [1772] [ERROR] Can't connect to ('192.168.0.100', 5000)
[2024-08-26 09:19:44 -0400] [2124] [DEBUG] Current configuration:
  config: gunicorn_config.py
  wsgi_app: None
  bind: ['192.168.0.100:5000']
  backlog: 2048
  workers: 4
  worker_class: uvicorn.workers.UvicornWorker
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /home/oyone/fastapi_project
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 1000
  group: 1003
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1', '::1']
  accesslog: /home/oyone/fastapi_project/logs/access.log
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: /home/oyone/fastapi_project/logs/error.log
  loglevel: debug
  capture_output: True
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  logconfig_json: None
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: main:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0xffff81db8220>
  on_reload: <function OnReload.on_reload at 0xffff81db8360>
  when_ready: <function WhenReady.when_ready at 0xffff81db84a0>
  pre_fork: <function Prefork.pre_fork at 0xffff81db8680>
  post_fork: <function Postfork.post_fork at 0xffff81db87c0>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0xffff81db8900>
  worker_int: <function WorkerInt.worker_int at 0xffff81db8a40>
  worker_abort: <function WorkerAbort.worker_abort at 0xffff81db8b80>
  pre_exec: <function PreExec.pre_exec at 0xffff81db8cc0>
  pre_request: <function PreRequest.pre_request at 0xffff81db8e00>
  post_request: <function PostRequest.post_request at 0xffff81db8ea0>
  child_exit: <function ChildExit.child_exit at 0xffff81db8fe0>
  worker_exit: <function WorkerExit.worker_exit at 0xffff81db9120>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0xffff81db9260>
  on_exit: <function OnExit.on_exit at 0xffff81db93a0>
  ssl_context: <function NewSSLContext.ssl_context at 0xffff81db9580>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1', '::1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  permit_obsolete_folding: False
  strip_header_spaces: False
  permit_unconventional_http_method: False
  permit_unconventional_http_version: False
  casefold_http_method: False
  forwarder_headers: ['SCRIPT_NAME', 'PATH_INFO']
  header_map: drop
[2024-08-26 09:19:44 -0400] [2124] [INFO] Starting gunicorn 23.0.0
[2024-08-26 09:19:44 -0400] [2124] [ERROR] Connection in use: ('192.168.0.100', 5000)
[2024-08-26 09:19:44 -0400] [2124] [ERROR] connection to ('192.168.0.100', 5000) failed: [Errno 98] Address already in use
[2024-08-26 09:19:44 -0400] [2124] [DEBUG] Retrying in 1 second.
[2024-08-26 09:19:45 -0400] [2124] [ERROR] Connection in use: ('192.168.0.100', 5000)
[2024-08-26 09:19:45 -0400] [2124] [ERROR] connection to ('192.168.0.100', 5000) failed: [Errno 98] Address already in use
[2024-08-26 09:19:45 -0400] [2124] [DEBUG] Retrying in 1 second.
[2024-08-26 09:19:46 -0400] [2124] [ERROR] Connection in use: ('192.168.0.100', 5000)
[2024-08-26 09:19:46 -0400] [2124] [ERROR] connection to ('192.168.0.100', 5000) failed: [Errno 98] Address already in use
[2024-08-26 09:19:46 -0400] [2124] [DEBUG] Retrying in 1 second.
[2024-08-26 09:19:47 -0400] [2124] [ERROR] Connection in use: ('192.168.0.100', 5000)
[2024-08-26 09:19:47 -0400] [2124] [ERROR] connection to ('192.168.0.100', 5000) failed: [Errno 98] Address already in use
[2024-08-26 09:19:47 -0400] [2124] [DEBUG] Retrying in 1 second.
[2024-08-26 09:19:48 -0400] [2124] [ERROR] Connection in use: ('192.168.0.100', 5000)
[2024-08-26 09:19:48 -0400] [2124] [ERROR] connection to ('192.168.0.100', 5000) failed: [Errno 98] Address already in use
[2024-08-26 09:19:48 -0400] [2124] [DEBUG] Retrying in 1 second.
[2024-08-26 09:19:49 -0400] [2124] [ERROR] Can't connect to ('192.168.0.100', 5000)
[2024-08-26 09:28:21 -0400] [2825] [DEBUG] Current configuration:
  config: gunicorn_config.py
  wsgi_app: None
  bind: ['192.168.0.100:5000']
  backlog: 2048
  workers: 4
  worker_class: uvicorn.workers.UvicornWorker
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /home/oyone/fastapi_project
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 1000
  group: 1003
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1', '::1']
  accesslog: /home/oyone/fastapi_project/logs/access.log
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: /home/oyone/fastapi_project/logs/error.log
  loglevel: debug
  capture_output: True
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  logconfig_json: None
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: main:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0xffff993a8220>
  on_reload: <function OnReload.on_reload at 0xffff993a8360>
  when_ready: <function WhenReady.when_ready at 0xffff993a84a0>
  pre_fork: <function Prefork.pre_fork at 0xffff993a8680>
  post_fork: <function Postfork.post_fork at 0xffff993a87c0>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0xffff993a8900>
  worker_int: <function WorkerInt.worker_int at 0xffff993a8a40>
  worker_abort: <function WorkerAbort.worker_abort at 0xffff993a8b80>
  pre_exec: <function PreExec.pre_exec at 0xffff993a8cc0>
  pre_request: <function PreRequest.pre_request at 0xffff993a8e00>
  post_request: <function PostRequest.post_request at 0xffff993a8ea0>
  child_exit: <function ChildExit.child_exit at 0xffff993a8fe0>
  worker_exit: <function WorkerExit.worker_exit at 0xffff993a9120>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0xffff993a9260>
  on_exit: <function OnExit.on_exit at 0xffff993a93a0>
  ssl_context: <function NewSSLContext.ssl_context at 0xffff993a9580>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1', '::1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  permit_obsolete_folding: False
  strip_header_spaces: False
  permit_unconventional_http_method: False
  permit_unconventional_http_version: False
  casefold_http_method: False
  forwarder_headers: ['SCRIPT_NAME', 'PATH_INFO']
  header_map: drop
[2024-08-26 09:28:21 -0400] [2825] [INFO] Starting gunicorn 23.0.0
[2024-08-26 09:28:21 -0400] [2825] [ERROR] Connection in use: ('192.168.0.100', 5000)
[2024-08-26 09:28:21 -0400] [2825] [ERROR] connection to ('192.168.0.100', 5000) failed: [Errno 98] Address already in use
[2024-08-26 09:28:21 -0400] [2825] [DEBUG] Retrying in 1 second.
[2024-08-26 09:28:22 -0400] [2825] [ERROR] Connection in use: ('192.168.0.100', 5000)
[2024-08-26 09:28:22 -0400] [2825] [ERROR] connection to ('192.168.0.100', 5000) failed: [Errno 98] Address already in use
[2024-08-26 09:28:22 -0400] [2825] [DEBUG] Retrying in 1 second.
[2024-08-26 09:28:23 -0400] [2825] [ERROR] Connection in use: ('192.168.0.100', 5000)
[2024-08-26 09:28:23 -0400] [2825] [ERROR] connection to ('192.168.0.100', 5000) failed: [Errno 98] Address already in use
[2024-08-26 09:28:23 -0400] [2825] [DEBUG] Retrying in 1 second.
[2024-08-26 09:28:24 -0400] [2825] [ERROR] Connection in use: ('192.168.0.100', 5000)
[2024-08-26 09:28:24 -0400] [2825] [ERROR] connection to ('192.168.0.100', 5000) failed: [Errno 98] Address already in use
[2024-08-26 09:28:24 -0400] [2825] [DEBUG] Retrying in 1 second.
[2024-08-26 09:28:25 -0400] [2825] [ERROR] Connection in use: ('192.168.0.100', 5000)
[2024-08-26 09:28:25 -0400] [2825] [ERROR] connection to ('192.168.0.100', 5000) failed: [Errno 98] Address already in use
[2024-08-26 09:28:25 -0400] [2825] [DEBUG] Retrying in 1 second.
[2024-08-26 09:28:26 -0400] [2825] [ERROR] Can't connect to ('192.168.0.100', 5000)
[2024-08-26 09:28:49 -0400] [2993] [DEBUG] Current configuration:
  config: gunicorn_config.py
  wsgi_app: None
  bind: ['192.168.0.100:5000']
  backlog: 2048
  workers: 4
  worker_class: uvicorn.workers.UvicornWorker
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /home/oyone/fastapi_project
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 1000
  group: 1003
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1', '::1']
  accesslog: /home/oyone/fastapi_project/logs/access.log
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: /home/oyone/fastapi_project/logs/error.log
  loglevel: debug
  capture_output: True
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  logconfig_json: None
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: main:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0xffffb6c3c220>
  on_reload: <function OnReload.on_reload at 0xffffb6c3c360>
  when_ready: <function WhenReady.when_ready at 0xffffb6c3c4a0>
  pre_fork: <function Prefork.pre_fork at 0xffffb6c3c680>
  post_fork: <function Postfork.post_fork at 0xffffb6c3c7c0>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0xffffb6c3c900>
  worker_int: <function WorkerInt.worker_int at 0xffffb6c3ca40>
  worker_abort: <function WorkerAbort.worker_abort at 0xffffb6c3cb80>
  pre_exec: <function PreExec.pre_exec at 0xffffb6c3ccc0>
  pre_request: <function PreRequest.pre_request at 0xffffb6c3ce00>
  post_request: <function PostRequest.post_request at 0xffffb6c3cea0>
  child_exit: <function ChildExit.child_exit at 0xffffb6c3cfe0>
  worker_exit: <function WorkerExit.worker_exit at 0xffffb6c3d120>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0xffffb6c3d260>
  on_exit: <function OnExit.on_exit at 0xffffb6c3d3a0>
  ssl_context: <function NewSSLContext.ssl_context at 0xffffb6c3d580>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1', '::1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  permit_obsolete_folding: False
  strip_header_spaces: False
  permit_unconventional_http_method: False
  permit_unconventional_http_version: False
  casefold_http_method: False
  forwarder_headers: ['SCRIPT_NAME', 'PATH_INFO']
  header_map: drop
[2024-08-26 09:28:49 -0400] [2993] [INFO] Starting gunicorn 23.0.0
[2024-08-26 09:28:49 -0400] [2993] [ERROR] Connection in use: ('192.168.0.100', 5000)
[2024-08-26 09:28:49 -0400] [2993] [ERROR] connection to ('192.168.0.100', 5000) failed: [Errno 98] Address already in use
[2024-08-26 09:28:49 -0400] [2993] [DEBUG] Retrying in 1 second.
[2024-08-26 09:28:50 -0400] [2993] [ERROR] Connection in use: ('192.168.0.100', 5000)
[2024-08-26 09:28:50 -0400] [2993] [ERROR] connection to ('192.168.0.100', 5000) failed: [Errno 98] Address already in use
[2024-08-26 09:28:50 -0400] [2993] [DEBUG] Retrying in 1 second.
[2024-08-26 09:28:51 -0400] [2993] [ERROR] Connection in use: ('192.168.0.100', 5000)
[2024-08-26 09:28:51 -0400] [2993] [ERROR] connection to ('192.168.0.100', 5000) failed: [Errno 98] Address already in use
[2024-08-26 09:28:51 -0400] [2993] [DEBUG] Retrying in 1 second.
[2024-08-26 09:28:52 -0400] [2993] [ERROR] Connection in use: ('192.168.0.100', 5000)
[2024-08-26 09:28:52 -0400] [2993] [ERROR] connection to ('192.168.0.100', 5000) failed: [Errno 98] Address already in use
[2024-08-26 09:28:52 -0400] [2993] [DEBUG] Retrying in 1 second.
[2024-08-26 09:28:53 -0400] [2993] [ERROR] Connection in use: ('192.168.0.100', 5000)
[2024-08-26 09:28:53 -0400] [2993] [ERROR] connection to ('192.168.0.100', 5000) failed: [Errno 98] Address already in use
[2024-08-26 09:28:53 -0400] [2993] [DEBUG] Retrying in 1 second.
[2024-08-26 09:28:54 -0400] [2993] [ERROR] Can't connect to ('192.168.0.100', 5000)
